apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patches:
  - target:
      kind: Deployment
      name: gateway
    patch: |-
      - op: replace
        path: /spec/template/metadata/annotations
        value:
          "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
