apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Expose Gateway as NodePort for easy host curl access
  - target:
      kind: Service
      name: gateway
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
