window.addEventListener('scroll',()=>{const e=document.getElementById('pb');const m=document.documentElement.scrollHeight-window.innerHeight;e.style.width=(window.scrollY/m*100)+'%';});
const obs=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target);}});},{threshold:.1});
document.querySelectorAll('.rv,.rg').forEach(el=>obs.observe(el));
function switchTab(id){document.querySelectorAll('.tbt').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tp').forEach(p=>p.classList.remove('active'));document.getElementById('tb'+id).classList.add('active');document.getElementById('tab-'+id).classList.add('active');}
new Chart(document.getElementById('cB').getContext('2d'),{type:'doughnut',data:{labels:['Responder weights','Responder KV (LOCKED)','Agents weights','Agents KV (LOCKED)','LoRA adapters','Unusable gap'],datasets:[{data:[1.2,5.5,0.5,3.7,0.5,0.8],backgroundColor:['#4338ca','#818cf8','#065f46','#34d399','#374151','#1f2937'],borderColor:'#0b1929',borderWidth:3,hoverOffset:8}]},options:{cutout:'72%',plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>` ${c.label}: ${c.parsed} GB`}}},animation:{duration:1200,easing:'easeInOutQuart'}}});
const cA=new Chart(document.getElementById('cA').getContext('2d'),{type:'doughnut',data:{labels:['Responder weights','Responder KV (elastic)','Agents weights','Agents KV (elastic)','LoRA adapters','Shared pool'],datasets:[{data:[1.2,0.3,0.5,0.3,0.5,9.4],backgroundColor:['#4338ca','rgba(129,140,248,.45)','#065f46','rgba(52,211,153,.45)','#374151','#f59e0b'],borderColor:'#0b1929',borderWidth:3,hoverOffset:8}]},options:{cutout:'72%',plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>{const l=['fixed','elastic 0-8 GB','fixed','elastic 0-8 GB','fixed','shared dynamic'];return ` ${c.label}: ${l[c.dataIndex]}`;},}}},animation:{duration:1400,easing:'easeInOutQuart'}}});
let exp=true;setInterval(()=>{const v=exp?3.5:0.3,p=exp?6.2:9.4;cA.data.datasets[0].data[1]=v;cA.data.datasets[0].data[3]=v;cA.data.datasets[0].data[5]=p;cA.update('active');exp=!exp;},2400);
anime({targets:'.hst > div',opacity:[0,1],translateY:[20,0],delay:anime.stagger(100,{start:600}),duration:800,easing:'easeOutExpo'});
if(window.Prism)Prism.highlightAll();
